module.exports = {
  plugins: ['stylelint-prettier', 'stylelint-order', 'stylelint-config-rational-order/plugin'],
  extends: ['stylelint-config-prettier'],
  rules: {
    indentation: 2,
    'string-quotes': 'double',
    'no-duplicate-selectors': true,
    'color-hex-case': 'upper',
    'color-hex-length': 'long',
    'selector-combinator-space-after': 'always',
    'selector-attribute-quotes': 'always',
    'selector-attribute-operator-space-before': 'never',
    'selector-attribute-operator-space-after': 'never',
    'selector-attribute-brackets-space-inside': 'never',
    'declaration-no-important': true,
    'declaration-colon-space-before': 'never',
    'declaration-colon-space-after': 'always',
    'property-no-vendor-prefix': true,
    'number-leading-zero': 'always',
    'function-url-quotes': 'always',
    'comment-whitespace-inside': 'always',
    'comment-empty-line-before': 'always',
    'rule-empty-line-before': ['always', { except: ['first-nested'] }],
    'selector-pseudo-class-parentheses-space-inside': 'never',
    'media-feature-range-operator-space-before': 'always',
    'media-feature-range-operator-space-after': 'always',
    'media-feature-parentheses-space-inside': 'never',
    'media-feature-colon-space-before': 'never',
    'media-feature-colon-space-after': 'always',
    'order/properties-order': [],
    'plugin/rational-order': [
      true,
      {
        'border-in-box-model': false,
        'empty-line-between-groups': false,
      },
    ],
  },
};
